name: Update MBB Data

on:
  schedule:
    - cron: '0 7 18-31 10 *'
    - cron: '0 7 * 11-12 *'
    - cron: '0 7 * 1-3 *'
    - cron: '0 7 1-12 4 *'
  repository_dispatch:
    types: [daily_mbb_data]
  workflow_dispatch:
    inputs:
      start_year:
        required: false
        type: string
      end_year:
        required: false
        type: string
      rescrape:
        required: false
        default: true
        type: boolean

jobs:
  update_mbb_data:
    runs-on: ${{ matrix.config.os }}
    name: Update MBB Data ${{ inputs.start_year }}-${{ inputs.end_year }} (Rescrape? ${{ inputs.rescrape }})
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: 'ubuntu-latest',   r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      START_YEAR: ${{ inputs.start_year }}
      END_YEAR: ${{ inputs.end_year }}
      RESCRAPE: ${{ inputs.rescrape }}

    steps:
      # - name: Maximize build space
      #   uses: easimon/maximize-build-space@master
      #   with:
      #     root-reserve-mb: 512
      #     swap-size-mb: 1024
      #     remove-dotnet: 'true'

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setting up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Setting up R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 1
          extra-packages: |
            sportsdataverse/hoopR
            sportsdataverse/sportsdataverse-data
            ropensci/piggyback

      - name: Check for Inputs
        if: ${{ env.START_YEAR == ''}}
        run: |
          echo START_YEAR=$(Rscript -e "cat(hoopR::most_recent_mbb_season())") >> $GITHUB_ENV
          echo END_YEAR=$(Rscript -e "cat(hoopR::most_recent_mbb_season())") >> $GITHUB_ENV
          echo RESCRAPE=false >> $GITHUB_ENV
      - name: Check hoopR_mbb_data_trigger for Inputs
        if: ${{ github.event.client_payload.event_name == 'daily_mbb_data'}}
        run: |
          echo START_YEAR = $(echo ${{ github.event.client_payload.commit_message}} | grep -o -E '[0-9]+ | head -1') >> $GITHUB_ENV
          echo END_YEAR = $(echo ${{ github.event.client_payload.commit_message}} | grep -o -E '[0-9]+ | head -1') >> $GITHUB_ENV
          echo RESCRAPE=true >> $GITHUB_ENV
      - name: Update MBB Data ${{ env.start_year }}-${{ env.end_year }} (Rescrape? ${{ env.rescrape }})
        env:
          GITHUB_PAT: ${{ secrets.SDV_GH_TOKEN }}
        run: |
          bash scripts/daily_mbb_R_processor.sh -s ${{ env.START_YEAR }} -e ${{ env.END_YEAR }} -r ${{ env.RESCRAPE }}